### ISSUE TITLE
Revoke private key or add comment indicating the reason it has been committed

### ISSUE THREAD

**Issue by strand** [Microsoft/PowerBI-visuals-ClusterMap#43]
It is a security best practice to never commit a secret, especially within a publicly viewable repository. However, the following file has been committed to your repo:

- `PowerBI-visuals-ClusterMap/certs/PowerBICustomVisualTest_private.key`

To resolve this issue, either revoke this key and remove it from the repo, OR add a comment indicating both why it is necessary to have this private key and why it is not a security risk.

**Comment by psmacmur** [comment]
This key is only used so that we can serve the dev visual over https, and is thus harmless.  Revoking the key is not an option, as it is a direct copy from the pbi tools repo.

**Comment by strand** [comment]
Please add a comment to the key indicating this as described in [this article](PowerBI-visuals-FacetKey/certs/PowerBICustomVisualTest_private.key).

**Comment by psmacmur** [comment]
Your link doesn't work

**Comment by strand** [comment]
🤦‍ D'oh. The link is fixed.
