### ISSUE TITLE
ClusterMap doesn't support chinese label

### ISSUE THREAD

**Issue by Ryan-Gao** [Microsoft/PowerBI-visuals-ClusterMap#46]
Hi team, it can display chinese label well in the first version, but now sth  goes wrong
![snipaste_20180108_162957](https://user-images.githubusercontent.com/28983335/34663352-6c811c54-f491-11e7-831e-3cb7be6aa063.png)

**Comment by psmacmur** [comment]
Thank you for bringing this issue to our attention. We have prepared a fix to address this issue; see [v1.1.4](https://github.com/Microsoft/PowerBI-visuals-ClusterMap/releases/tag/v1.1.4).  It should be available from the PowerBI marketplace in the coming weeks.
